create advert
htmlacademy-javascript/1698229-keksobooking-22 pull request #3
Opened 2021-02-07 14:27 UTC by Ju-nova

2021-02-07 15:04 UTC, ArtMan-8 requested changes

2021-02-07 15:04 UTC, ArtMan-8 commented on js/main.js
> +const feature = {
Перечисление начинается с большой буквы.
https://up.htmlacademy.ru/javascript/22/criteries#b8

2021-02-07 15:04 UTC, ArtMan-8 commented on js/main.js
> +let checkHours =[
все постоянные переменные обычно объявляются в начале файла

2021-02-07 15:04 UTC, ArtMan-8 commented on js/main.js
> +    price: getRandomNumber(0, 1000000),
В задании обрати внимание, в каком формате должен быть адрес

2021-02-07 15:04 UTC, ArtMan-8 commented on js/main.js
> +    checkout: randomCheckHours,
checkin и checkout могут быть разные

2021-02-07 15:04 UTC, ArtMan-8 commented on js/main.js
> +const createAdvert = () => {
Это круто! 💪

2021-02-07 16:36 UTC, Ju-nova commented on js/main.js
> +    checkout: randomCheckHours,
вот на это в тз обратила внимание, наверно они должны быть одинаковыми

2021-02-07 16:36 UTC, Ju-nova commented on js/main.js
> +    checkout: randomCheckHours,
3.5. Поля «Время заезда» и «Время выезда» синхронизированы: при изменении значения одного поля во втором выделяется соответствующее ему значение. Например, если время заезда указано «после 14», то время выезда будет равно «до 14» и наоборот.

2021-02-08 18:53 UTC, ArtMan-8 approved these changes

2021-02-08 18:59 UTC, merged